import 'root'
import 'os_gentoo'

# Class tool::portage::extend
#
#  Allows to extend /etc/make.conf
#
# @author Gunnar Wrobel <p@rdus.de>
# @version 1.0
# @package tool_portage_extend
#
class tool::portage::extend {

  case $operatingsystem {
    gentoo:
    {
      line {'source_make_conf_puppet':
        file => '/etc/make.conf',
        line => 'source /etc/portage/make.conf.puppet',
        tag => 'buildhost'
      }

      @line {'make_conf_puppet_comment':
        file => '/etc/portage/make.conf.puppet',
        line => '#This file gets automatically generated by puppet',
        tag => 'buildhost'
      }

      Line <| file == '/etc/portage/make.conf.puppet' |>
    }  
  }
}
